[PX4]
; PX4_ADDRESS : str
; The address of the remote system. If None, it will default to
; udpin: //0.0.0.0:14540.

; Supported URL formats:

;         - Serial: serial: ///path/to/serial/dev[:baudrate]
;         - UDP in: udpin: //bind_host:bind_port
;         - UDP out: udpout: //dest_host:dest_port
;         - TCP in: tcpin: //bind_host:bind_port
;         - TCP out: tcpout: //dest_host:dest_port

; for VOXL2 change the following lines in /etc/modalai/voxl-vision-hub.conf
;         "en_localhost_mavlink_udp": true, // false -> true
;         "localhost_udp_port_number": 14551, // set the same port bellow
ADDRESS = udp://:14551

; DETECTION_ACTION : str

; The action to take when a valid detection is received.

; Available actions:

;     'hold'
;         Switch the PX4 vehicle to Hold mode.

;     'land'
;         Command the vehicle to land.

; Future actions can be added to the action registry below.
DETECTION_ACTION = hold


[YOLO]
; YOLO_DETECTION_TOPIC : str
; The ROS 2 topic to listen for YOLO detections on.

; Message type:
;     voxl_msgs/Aidetection
DETECTION_TOPIC = /yolo_tflite_data

; TFLITE_OUTPUT_PIPE_PREFIX: str

; The prefix of the output pipe created by voxl-tflite-server.
TFLITE_OUTPUT_PIPE_PREFIX = yolo