[GENERAL]
; Artificial latency to inject (in milliseconds) 
; Applied once before YOLO processing and once before MAVLink transmission
ARTIFICIAL_LATENCY_MS = 1000


; CONNECTOR_TYPE : str
; The type of connector to use for transmission of commands.
; Available options:
;    'VISION_HUB' : Use the VOXL Vision Hub to transmit commands to PX4.
;   'PX4' : Use the MAVLink protocol to transmit commands directly to PX4.
CONNECTOR_TYPE = VISION_HUB


[PX4]
; PX4_ADDRESS : str
; The address of the remote system. If None, it will default to
; udpin: //0.0.0.0:14540.

; Supported URL formats:

;         - Serial: serial: ///path/to/serial/dev[:baudrate]
;         - UDP in: udpin: //bind_host:bind_port
;         - UDP out: udpout: //dest_host:dest_port
;         - TCP in: tcpin: //bind_host:bind_port
;         - TCP out: tcpout: //dest_host:dest_port

; for VOXL2 change the following lines in /etc/modalai/voxl-vision-hub.conf
;         "en_localhost_mavlink_udp": true, // false -> true
;         "localhost_udp_port_number": 14551, // set the same port bellow
ADDRESS = udpout://yvoxl2.local:14550

; DETECTION_ACTION : str

; The action to take when a valid detection is received.

; Available actions:
;     'hold' : Switch the PX4 vehicle to Hold mode.
;     'land' : Command the vehicle to land.
;     'offboard' : Switch the PX4 vehicle to Offboard mode.

DETECTION_ACTION = hold

[YOLO]
; RTSP Camera Stream URL
RTSP_URL = rtsp://yvoxl2.local:8900/live

MODEL_PATH = yolo26m.pt
CONFIDENCE_THRESHOLD = 0.6

; Target device: 'auto' (dynamically selects CUDA if available), 'cpu', '0', '1', or '0,1'
DEVICE = auto

; Display local OpenCV window on desktop (Set to false when running headless or over SSH)
ENABLE_DEBUG_WINDOW = true

; Enable HTTP web stream for remote viewing in a browser
ENABLE_WEB_STREAM = false
WEB_PORT = 8080